# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Barrio.create([
  { :nombre => "margaritas", :municipio_id => 1, :created_at => "2013-07-31 16:12:12", :updated_at => "2013-07-31 16:12:12" },
  { :nombre => "magnolia", :municipio_id => 2, :created_at => "2013-07-31 16:12:35", :updated_at => "2013-07-31 16:12:35" }
], :without_protection => true )

Estado.create([
  { :nombre => "en espera", :created_at => "2013-07-23 16:43:39", :updated_at => "2013-07-23 16:43:39" },
  { :nombre => "reprogramado", :created_at => "2013-07-23 16:44:26", :updated_at => "2013-07-23 16:44:26" },
  { :nombre => "terminado", :created_at => "2013-07-29 16:08:31", :updated_at => "2013-07-29 16:08:31" }
], :without_protection => true )



Municipio.create([
  { :nombre => "itagui", :created_at => "2013-07-31 14:04:00", :updated_at => "2013-07-31 14:04:00" },
  { :nombre => "envigado", :created_at => "2013-07-31 14:04:32", :updated_at => "2013-07-31 14:04:32" }
], :without_protection => true )



Ofertado.create([
  { :nombre => "instalacion de gimnasio", :created_at => "2013-07-23 16:42:33", :updated_at => "2013-07-25 16:27:46" },
  { :nombre => "instalacion de cocina integral", :created_at => "2013-07-23 16:42:28", :updated_at => "2013-07-29 16:19:41" },
  { :nombre => "instalacion articulos en madera", :created_at => "2013-07-29 16:20:56", :updated_at => "2013-07-29 16:21:04" }
], :without_protection => true )


TipoCalificacion.create([
  { :nombre => "buena", :created_at => "2013-07-23 16:42:42", :updated_at => "2013-07-23 16:42:42" },
  { :nombre => "mala", :created_at => "2013-07-23 16:42:47", :updated_at => "2013-07-23 16:42:47" },
  { :nombre => "excelente", :created_at => "2013-07-29 16:44:07", :updated_at => "2013-07-29 16:44:07" }
], :without_protection => true )



User.create([

  
  { :username => "claudia", :email => "claudiamaryory@misena.edu.co", :password => "123", :salt => nil, :created_at => "2013-08-23 16:26:10", :updated_at => "2013-08-23 16:26:10", :remember_me_token => nil, :remember_me_token_expires_at => nil, :reset_password_token => nil, :reset_password_token_expires_at => nil, :reset_password_email_sent_at => nil }
])

  



